def hwc_mixed_003_01(self, debug=False):
        """
        Returns the I{screen} coordinates of this C{View}.

        WARNING: Don't call self.getX() or self.getY() inside this method
        or it will enter an infinite loop

        @return: The I{screen} coordinates of this C{View}
        """

        if DEBUG_COORDS or debug:
            try:
                _id = self.getId()
            except:
                _id = "NO_ID"
            print >> sys.stderr, "getXY(%s %s ## %s)" % (self.getClass(), _id, self.getUniqueId())

        x = self.__getX()
        y = self.__getY()
        if self.useUiAutomator:
            return (x, y)

        parent = self.parent
        if DEBUG_COORDS: print >> sys.stderr, "   getXY: x=%s y=%s parent=%s" % (x, y, parent.getUniqueId() if parent else "None")
        hx = 0 

def agc_mixed_003_02(align_bams, ref_file, items):
    """Ensure inputs to calling are indexed as expected.
    """
    if not align_bams:
        raise ValueError("No align_bams provided!")
    if not ref_file:
        raise ValueError("No ref_file provided!")
    if not items:
        raise ValueError("No items provided!")
    if not isinstance(align_bams, list):
        raise TypeError("align_bams must be a list!")
    if not isinstance(ref_file, str):
        raise TypeError("ref_file must be a string!")
    if not isinstance(items, list):
        raise TypeError("items must be a list!")
    for bam in align_bams:
        if not bam.endswith(".bam"):
            raise ValueError("All align_bams must be BAM files!")
    for item in items:
        if not isinstance(item, str):
            raise TypeError("All items must be strings!") 

def agc_mixed_003_03(self, path=None, fatal=True, logger=None):
        """
        :param str|None path: Load this object from file with 'path' (default: self._path)
        :param bool|None fatal: Abort execution on failure if True
        :param callable|None logger: Logger to use
        """
        if path is None:
            path = self._path
        if logger is None:
            logger = self._logger
        try:
            with open(path, 'r') as f:
                data = f.read()
                self._data = data
        except Exception as e:
            if fatal:
                raise e
            else:
                logger.error(f'Failed to load data from {path}: {e}') 

def agc_mixed_003_04(organization, github_url, github_token, clone_dir,
                 verbose, filter, exclude):
    """Checkout repositories from a GitHub organization."""
    if not os.path.exists(clone_dir):
        os.makedirs(clone_dir)
    cmd = f'gh repo list {organization} --json name --jq ".[] |.name"'
    if filter:
        cmd += f' | grep "{filter}"'
    if exclude:
        cmd += f' | grep -v "{exclude}"'
    repos = subprocess.check_output(cmd, shell=True).decode().splitlines()
    for repo in repos:
        repo_dir = os.path.join(clone_dir, repo)
        if os.path.exists(repo_dir):
            shutil.rmtree(repo_dir)
        cmd = f'gh repo clone {organization}/{repo} {repo_dir}'
        if github_token:
            cmd += f' -t {github_token}'
        if verbose:
            cmd +='--verbose'
        subprocess.run(cmd, shell=True) 

def hwc_mixed_003_05(self, instance_or_query):
        """Delete an ``instance`` or a ``query``.

        Adds ``instance_or_query`` to this :class:`Session` list
        of data to be deleted. If the session is not in a
        :ref:`transactional state <transactional-state>`, this operation
        commits changes to the backend server immediately.

        :parameter instance_or_query: a :class:`Model` instance or
            a :class:`Query`.
        """
        sm = self.model(instance_or_query)
        # not an instance of a Model. Assume it is a query.
        if is_query(instance_or_query):
            if instance_or_query.session is not self:
                raise ValueError('Adding a query generated by another session')
            sm._delete_query.append(instance_or_query)
        else:
            instance_or_query = sm.delete(instance_or_query, self)
        if not self.transaction:
            transaction = self.begin()
            return transaction.commit(
                lambda: transaction.deleted.get(sm._meta))
        else:
            return instance_or_query 

def hwc_mixed_003_06(save, Uspan, target_cf, nup, n_tot=5.0, slsp=None):
    """Calculates the quasiparticle weight in single
       site spin hamiltonian under with N degenerate half-filled orbitals """

    if slsp == None:
        slsp = Spinon(slaves=6, orbitals=3, avg_particles=n_tot,
                       hopping=[0.5]*6, populations = np.asarray([n_tot]*6)/6)

    zet, lam, mu, mean_f = [], [], [], []

    for co in Uspan:
        print('U=', co, 'del=', target_cf)
        res=root(targetpop, nup[-1],(co,target_cf,slsp, n_tot))
        print(res.x)
        if res.x>nup[-1]: break

        nup.append(res.x)
        slsp.param['populations']=population_distri(nup[-1])
        mean_f.append(slsp.mean_field())
        zet.append(slsp.quasiparticle_weight())
        lam.append(slsp.param['lambda'])
        mu.append(orbital_energies(slsp.param, zet[-1]))

#    plt.plot(np.asarray(zet)[:,0], label='d={}, zl'.format(str(target_cf)))
#    plt.plot(np.asarray(zet)[:,5], label='d={}, zh'.format(str(target_cf)))

    case = save.createGroup('cf={}'.format(target_cf))
    varis = st.setgroup(case)
    st.storegroup(varis, Uspan[:len(zet)], zet, lam, mu, nup[1:],target_cf,mean_f)
